### ISSUE TITLE
Stacked Widgets cause issues

### ISSUE THREAD

**Issue by LaRuaNa** [BrunoJurkovic/flip_card#1]
Hi @fedeoo,

I have the problem that interactable widgets like buttons are available (even tough invisible) on the backside of the card. I think thats because you use a stack to store both sides of a card. 

A good approach to that problem would be maybe conditional rendering of front and back side.

**Comment by feibyte** [comment]
@LaRuaNa  Thanks for your feedback.  Not sure I got your point:
1. Any interactable widget won't work because there's no way to stop event bubble.
2. When a side is invisible, I just rotate it 90deg, which means it's perpendicular to the view. (
It's not rotated by 180deg. You know, With CSS, A element was rotated by 180deg will be invisible. But that won't work in flutter.
)

Did I miss something?
If so, could you build a simple demo?  Are you willing to be a contributor?

**Comment by LaRuaNa** [comment]
Hi @fedeoo, I'll come up with a demo or maybe PR soon. Unfortunately quite busy currently.

**Comment by nickponomar** [comment]
Hey @fedeoo , @LaRuaNa 
Looks like I am facing the same issue. You can try it out with this piece of code:
`
content = FlipCard(
          front: Center(
            child: Container(
              height: 100.0,
              color: Colors.red,
              child: Center(
                child: IconButton(
                  icon: Icon(Icons.ac_unit),
                  onPressed: () {
                    print('here I am');
                  },
                ),
              ),
            ),
          ),
          back: Center(
            child: Container(
              height: 100.0,
              color: Colors.red,
              child: Center(
                child: IconButton(
                  icon: Icon(Icons.zoom_out_map),
                  onPressed: () {
                    print('here I am 2');
                  },
                ),
              ),
            ),
          ),
        );
`
First button on the front side is basically unclickable. Any ideas on how to fix it? Thank you in advance!

**Comment by LaRuaNa** [comment]
Oh I'm sorry, absolutely forgot about that since I postponed the project. Can you reproduce that @fedeoo ?

**Comment by gbuela** [comment]
I need to solve this too. I have a card with interactive elements on either side. Each side includes a flip button. With this implementation, none of my interactions work, apparently because the GestureDetector catches all taps on the card. If I remove the detector and just leave the Stack, the front interactions don't work presumably because the front is the bottom of the stack. When I remove the back from the stack, I get the interactions including the flip from my custom flip button... adding back the back, I can flip back to the front but then I'm stuck again.
Anybody knows how to make it work without the stack?

**Comment by gbuela** [comment]
All right, I found a way to solve my issues with a different approach, here it is in case it helps anyone:
https://gist.github.com/gbuela/64557c130d62e23d33b3e47d076e95e2
Maybe it can be simplified somewhat. I did away with the gesture detector (because the flipping is triggered by your front & back widgets only) and the stack, so both widgets are interactable.
