### ISSUE TITLE
Switch the value of the isFront variable at the end of the animation instead of in the toggleCard method

### ISSUE THREAD

**Issue by loicsacre** [BrunoJurkovic/flip_card#20]
The value switcher in the toggleCard method

`
setState(() {
      isFront = !isFront;
    });
`

should instead be placed where the animation is completed or dismissed. Indeed, when the toggle animation is triggered, the isFront boolean value changes even if the animation is not finished and it could be problematic for code relying on that variable.

**Comment by kpk-i710** [comment]
yes, I had to study, you need to check whether the animation is completed, and then only turn the card over manually so that isfront is correct

**Comment by BrunoJurkovic** [comment]
@kpk-i710 Could you please help me out solving this issue, I don't quite seem to understand what you or the original creator of this issue mean by _should instead be placed where the animation is completed or dismissed._ Could you please write the issue in a format of:
EXPECTED BEHAVIOUR:


ACTUAL BEHAVIOUR:


Thanks!

**Comment by kpk-i710** [comment]
> @kpk-i710 Could you please help me out solving this issue, I don't quite seem to understand what you or the original creator of this issue mean by _should instead be placed where the animation is completed or dismissed._ Could you please write the issue in a format of: EXPECTED BEHAVIOUR:
> 
> ACTUAL BEHAVIOUR:
> 
> Thanks!
it’s hard to describe it until you try it. You just need to click on the card twice in a row and look in the conflip.state.isFront variable will not have the correct value.
Therefore, to solve this, I used when clicking on the card
  if (! conflip.controller.isAnimating) {
  conflip.toggleCard ();

}
since I cannot change the value of conflip.state.isFront before the animation ends, otherwise the data will be incorrect

**Comment by kpk-i710** [comment]
> @kpk-i710 Could you please help me out solving this issue, I don't quite seem to understand what you or the original creator of this issue mean by _should instead be placed where the animation is completed or dismissed._ Could you please write the issue in a format of: EXPECTED BEHAVIOUR:
> 
> ACTUAL BEHAVIOUR:
> 
> Thanks!

it’s hard to describe it until you try it. You just need to click on the card twice in a row and look in the conflip.state.isFront variable will not have the correct value.
Therefore, to solve this, I used when clicking on the card
  if (! conflip.controller.isAnimating) {
  conflip.toggleCard ();

}
since I cannot change the value of conflip.state.isFront before the animation ends, otherwise the data will be incorrect

**Comment by BrunoJurkovic** [comment]
Hmm, interesting, would you be willing to make a PR to change this behavior? @kpk-i710

**Comment by kpk-i710** [comment]
> Hmm, interesting, would you be willing to make a PR to change this behavior? @kpk-i710

to be honest, I haven't created a single package for flutter yet, so there is no experience in creating and for changes, I think I will soon start making my own packages too

**Comment by BrunoJurkovic** [comment]
@kpk-i710 This behavior should now be changed in the next update that I will release shortly, please let me know if this issue is somehow still persistent after updating to the 0.6.0 version. Thank you for the bug report!
