### ISSUE TITLE
List of FlipCards

### ISSUE THREAD

**Issue by AliRn76** [BrunoJurkovic/flip_card#26]
Hi
How can I create a list of FlipCards with GlobalKey ,
Is it even possible to create a List of GlobalKeys?

**Comment by feibyte** [comment]
Not sure I got your point. It's just a variable. 
Do you wanna use the same key on a list of cards?  So you can control all cards. Is that what you mean to do?

**Comment by AliRn76** [comment]
yea , I want list like this:
ListView(
    children:[
        FlipCard(),
        FlipCard(),
        ...
    ])
How can I handle their keys?

**Comment by feibyte** [comment]
Good point!  In order to do this, the state should be separated and all those cards could reuse a single one. 
I didn't make this component stateless as the state can't be changed during the animation. 
Unfortunately, there are no elegant methods ATM.  I'll think about this. 
I'm thinking of exposing some private methods and you can extend this FlipCard and override build method.  I'll test it when I got a chance.

**Comment by AliRn76** [comment]
👍🏼✌🏼On Jul 19, 2020 18:09, 小乙哥 <notifications@github.com> wrote:
Good point!  In order to do this, the state should be separated and all those cards could reuse a single one.
I didn't make this component stateless as the state can't be changed during the animation.
Unfortunately, there are no elegant methods ATM.  I'll think about this.
I'm thinking of exposing some private methods and you can extend this FlipCard and override build method.  I'll test it when I got a chance.

**Comment by AliRn76** [comment]
👍👌

**Comment by feibyte** [comment]
@AliRn76  I made some change on the branch **fe-extract-abstract-cmp**
Could you help to check the example is what you expect? Thanks.

**Comment by terryb84** [comment]
hi @fedeoo , will you please guide me where i can fine example? thank you.
