### ISSUE TITLE
same size for front and back 

### ISSUE THREAD

**Issue by jiampong212** [BrunoJurkovic/flip_card#52]
is it possible to have the same size for the front and back? i'm trying to do it without global keys. it would probably be useful if t he flipcard itself automatically gets the height depending on which side is larger

**Comment by BrunoJurkovic** [comment]
Could you please try to reformat your question, I don't really understand what you are asking? Are you trying to ask if you can have the widget for the back and front rotation be the same size because that is very simple to do? Please provide a better description of your problem so that we can help and solve it, thanks.

**Comment by BrunoJurkovic** [comment]
Fixed in PR #51
